name: OpenWrt Builder

on:
  repository_dispatch:
  workflow_dispatch:

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: .config
  DIY_P1_SH: diy-part1.sh
  DIY_P2_SH: diy-part2.sh
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 150

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Verify System Tools
      run: |
        echo "=== Core Tools Check ==="
        git --version || exit 1
        gcc --version || exit 1
        make --version || exit 1
        python2 --version 2>/dev/null || echo "Python2 not found - will install later"

    - name: Setup Python2 Environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        # 启用Universe软件源
        sudo add-apt-repository universe -y
        sudo apt-get update -qq

        # 安装Python2及相关依赖
        sudo apt-get install -y --no-install-recommends \
          python2 \
          python2-dev \
          python-is-python2 \
          libpython2.7

        # 验证安装
        echo "Python2 version: $(python2 --version 2>&1)"
        [ -f /usr/bin/python2 ] || exit 1
        ln -sf /usr/bin/python2 /usr/bin/python
        echo "Python alias: $(python --version 2>&1)"

    - name: Setup Build Environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* \
          /usr/share/dotnet \
          /usr/local/lib/android \
          /opt/ghc \
          /opt/hostedtoolcache/CodeQL
        
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install --no-install-recommends \
          ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
          bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext \
          gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 \
          libelf-dev libfuse-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev \
          libmpfr-dev libncurses5-dev libncursesw5-dev libpython2-dev libpython3-dev \
          libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp ninja-build p7zip \
          p7zip-full patch pkgconf python-is-python2 python3 python3-pyelftools \
          python3-setuptools qemu-utils rsync scons squashfs-tools subversion swig \
          texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev

        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown -R $USER:$(id -gn) /workdir

    - name: Clone Source Code
      working-directory: /workdir
      run: |
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
        ln -sfn /workdir/openwrt $GITHUB_WORKSPACE/openwrt
        ls -l $GITHUB_WORKSPACE

    - name: Validate Repository
      working-directory: /workdir/openwrt
      run: |
        [ -d .git ] || { echo "Git repository missing"; exit 1; }
        [ -f feeds.conf.default ] || { echo "Default feeds missing"; exit 1; }

    - name: Apply Custom Configuration
      working-directory: $GITHUB_WORKSPACE
      run: |
        [ -f "$FEEDS_CONF" ] && cp -v "$FEEDS_CONF" openwrt/feeds.conf.default
        [ -f "$DIY_P1_SH" ] && chmod +x "$DIY_P1_SH"
        [ -f "$DIY_P1_SH" ] && (cd openwrt && ../"$DIY_P1_SH")

    - name: Update Feeds
      working-directory: $GITHUB_WORKSPACE/openwrt
      run: ./scripts/feeds update -a

    - name: Install Feeds
      working-directory: $GITHUB_WORKSPACE/openwrt
      run: ./scripts/feeds install -a

    - name: Load Device Configuration
      working-directory: $GITHUB_WORKSPACE
      run: |
        [ -d files ] && cp -rv files openwrt/files/
        [ -f "$CONFIG_FILE" ] && cp -v "$CONFIG_FILE" openwrt/.config
        [ -f "$DIY_P2_SH" ] && chmod +x "$DIY_P2_SH"
        [ -f "$DIY_P2_SH" ] && (cd openwrt && ../"$DIY_P2_SH")

    - name: Verify Build Configuration
      working-directory: $GITHUB_WORKSPACE/openwrt
      run: |
        [ -f .config ] || { echo "Missing .config file"; exit 1; }
        grep -q 'CONFIG_TARGET.*=y' .config || { echo "Invalid target config"; exit 1; }

    - name: Download Packages
      working-directory: $GITHUB_WORKSPACE/openwrt
      run: |
        make defconfig
        make download -j$(nproc)
        find dl -size -1024c -delete

    - name: Pre-Compile Check
      run: |
        echo "=== Disk Space Status ==="
        df -h
        echo "=== Workspace Usage ==="
        du -sh $GITHUB_WORKSPACE

    - name: Compile Firmware
      working-directory: $GITHUB_WORKSPACE/openwrt
      timeout-minutes: 120
      run: |
        echo "Using $(nproc) threads for compilation"
        make -j$(nproc) V=s || make -j1 V=s
        echo "DEVICE_NAME=_$(grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/')" >> $GITHUB_ENV
        echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

    - name: Prepare Artifacts
      if: success() && !cancelled()
      run: |
        cd $GITHUB_WORKSPACE/openwrt/bin/targets
        rm -rf ./*/packages
        echo "FIRMWARE_PATH=$(pwd)/$(ls -d */)" >> $GITHUB_ENV

    - name: Upload Bin Directory
      if: env.UPLOAD_BIN_DIR == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: OpenWrt-Bin-${{ env.DEVICE_NAME }}-${{ env.FILE_DATE }}
        path: $GITHUB_WORKSPACE/openwrt/bin

    - name: Upload Firmware
      if: env.UPLOAD_FIRMWARE == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: OpenWrt-Firmware-${{ env.DEVICE_NAME }}-${{ env.FILE_DATE }}
        path: ${{ env.FIRMWARE_PATH }}

    - name: Create Release
      if: env.UPLOAD_RELEASE == 'true'
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "${{ env.FILE_DATE }}"
        files: |
          ${{ env.FIRMWARE_PATH }}/*.bin
          ${{ env.FIRMWARE_PATH }}/*.img

    - name: Cleanup Workflows
      uses: Mattraks/delete-workflow-runs@v2
      with:
        keep_minimum_runs: 3
        retain_days: 3

    - name: Cleanup Releases
      uses: dev-drprasad/delete-older-releases@v0.2.1
      with:
        keep_latest: 5
        delete_tags: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
